### ISSUE TITLE
記事作成

### ISSUE THREAD

**Issue by yui-szk** [goose-hack/frontend-book#4]
## 概要

1. `/introduction` 導入 (全体像など)
2. `/getting-start` webサイトを作ってみる
   1. `/getting-start/installation` 開発環境構築 (VS code) + Prettier + Go Live
   2. `getting-start/html` HTML (h1, h2, div, p, a, img)
   3. `getting-start/css` CSS (color, background-color, font-size, etc) (課題必須はここまで)
   4. `getting-start/javascript` JavaScriptで動きを作成 (文字数カウンター)
   5. `getting-start/exercise` 演習
3. 開発環境を便利にする
   1. Git, GitHubで履歴を管理する
   2. GitHub Pagesで公開
6. 実務で使う技術で作り直してみる
   1. Node.jsインストール
   3. React Tutorial
   4. TypeScript Tutorial
7. React, TypeScript, tailwindcssで作り直し
   1. サーバー側でプログラムを動かしてみる
   2. Next.js Tutorial
   3. APIと通信する
8. CI/CDパイプラインを構築する
   1. CI/CDとは
   2. Jest
   3. GitHub Actions でJestを動かす
9. GitHubでチーム開発をしてみる
   1. ブランチ分ける
   2. PRを出す
   3. コードをレビューし合う

**Comment by yui-szk** [comment]
サンプルサイトとかあるべき？

**Comment by kanaru-ssk** [comment]
@yui-szk なんのサンプル？

**Comment by yui-szk** [comment]
@kanaru-ssk 
2のwebサイト作成の記事書いてて、単純にタグとかスタイルの説明だけするのか、こういうサイト作ってみましょう、でサンプルつくるのか、どっちの方がいいのかなーと思いまして

**Comment by kanaru-ssk** [comment]
@yui-szk 進めてくれてありがとう :bug: 
サンプル欲しいね。
内容もうちょい練るか

**Comment by kanaru-ssk** [comment]
@yui-szk できるだけ外部リソース (公式ドキュメント・チュートリアルとか)を有効活用しつつ体系的に学べる感じにしたい。
ので、まずは必要そうな外部リソースをリストアップしたい。

- [React Foundations](https://nextjs.org/learn/react-foundations)
   - Vercelが出してるReact Tutorial
   - React -> Next.jsの流れでいけるから良さそう
- [Dashboard App](https://nextjs.org/learn/dashboard-app)
   - Vercel公式のNext.jsチュートリアル
- [React Tutorial](https://react.dev/learn/tutorial-tic-tac-toe)
   - React公式チュートリアル
- [TypeScript Document](https://www.typescriptlang.org/docs/)
   - TypeScript公式ドキュメント

パッと思いつくところだとこの辺だけど、他やってみ良さそうなの何ある？

**Comment by kanaru-ssk** [comment]
[mdn web docs](https://developer.mozilla.org/ja/docs/Learn/Getting_started_with_the_web)もいい

**Comment by kanaru-ssk** [comment]
**メモ**
`src/articles/`にmdxを入れて、`[...slug]`でSSGするのが良さそう
```
src/
├ app/
│ ├ [...slug]/
│ │ └ page.tsx
│ ├ layout.tsx
│ └ page.tsx
└ articles/
　 ├ 01-01-getting-start.mdx
　 ├ 02-01-create-web-site.mdx
　 └ ...
```

**Comment by kanaru-ssk** [comment]
```
[
  { chapter: 0, section: 0, slug: [ 'introduction' ] },
  { chapter: 1, section: 0, slug: [ 'getting-start' ] },
  { chapter: 1, section: 1, slug: [ 'getting-start', 'installation' ] },
  { chapter: 1, section: 2, slug: [ 'getting-start', 'hello-world' ] }
]

[
  {
    chapterTitle:  'introduction',
    sections: [],
  },
  {
    chapterTitle:  'getting-start',
    sections: [
      'installation',
      'hello-world'
    ]
  }
]
```

**Comment by yui-szk** [comment]
sampleサイトの参考
- https://tatin.jp/
- https://cafe.anniversaire.co.jp/omotesando/
- https://caferob.com/

**Comment by yui-szk** [comment]
**メモ**
- 上のサイトを参考にsampleサイトのベース(index.html、style.css)作成

残り
- summary(introduction)
- ch01-00: 目次
- ch01-01(VSCode): VSCodeのインストール方法、プラグイン
- ch01-02(HTML): headとbodyの説明、ディレクトリの作成指示、その他タグ紹介
- ch01-03(CSS): CSSの説明、その他プロパティ紹介
- ch01-04(JS): JSの説明、カウンターの作成方法
- ch02以降の記事
**HTMLのタグ、CSSのプロパティについてはsampleによって変更の可能性あり**

**Comment by kanaru-ssk** [comment]
@yui-szk サイドメニューマージした。
ローカルで`develop` -> `feature/4`にマージして、appにあるmdxを`articles/`配下に移しておいて :pray:

**Comment by yui-szk** [comment]
元々`articles`にあるファイルは残しておいた方がいいですか？

**Comment by kanaru-ssk** [comment]
@yui-szk 
不要なやつは消していいよ。
introductionとgetting-startは命名として採用したいから、
```
articles/
├ 00-00-introduction.mdx
├ 01-00-getting-start.mdx
├ 01-01-installation.mdx
└ 01-02-html.mdx
```
とかでどうかな？
